### ISSUE TITLE
`--list-different` flag?

### ISSUE THREAD

**Issue by OliverJAsh** [thorn0/organize-imports-cli#1]
Hi, thanks for your work on this project!

I was wondering if it would be possible to add a `--list-different` flag, like what you can see in Prettier.

At build time, we want to validate that the code has been formatted correctly (and that this command has been run). This flag would enable us to do that.

**Comment by thorn0** [comment]
The problem here is that if you usually run Prettier after `organize-imports-cli`, you most probably will be getting lots of false negatives with this option. TS formats each import statement as a single line. Then, if some of those lines are long enough, Prettier breaks them into multiple lines. Guess what's going to happen if you run `organize-imports-cli --list-different` after that.

**Comment by thorn0** [comment]
@OliverJAsh Check v0.5.0. I attempted to workaround the issue described above by excluding files whose difference consists only of whitespace. They are still processed without `--list-different`, but `--list-different` ignores them.

**Comment by OliverJAsh** [comment]
> The problem here is that if you usually run Prettier after `organize-imports-cli`, you most probably will be getting lots of false negatives with this option. TS formats each import statement as a single line. Then, if some of those lines are long enough, Prettier breaks them into multiple lines. Guess what's going to happen if you run `organize-imports-cli --list-different` after that.

Ah, interesting.

Just to check I understand correctly, is this example the same thing as what you're saying? "Organize imports" would convert:

```ts
import {
  buildRouteActions,
  handleDataFetchingError,
  foo,
  bar,
  baz,
  bob,
} from 'helpers/data-fetching';
import api from 'client/services/api';
```

to

```ts
import api from 'client/services/api';
import { bar, baz, bob, buildRouteActions, foo, handleDataFetchingError } from 'helpers/data-fetching';
```

(re-ordered and reformatted)

Then Prettier would convert it to:

```ts
import api from 'client/services/api';
import {
  bar,
  baz,
  bob,
  buildRouteActions,
  foo,
  handleDataFetchingError,
} from 'helpers/data-fetching';
```

(same formatting as initial but different order)

Then when you run `organize-imports-cli --list-different`, it will report differences. Is that the problem?

This makes me think that organize imports should not change any formatting—it should _only_ re-order and remove (although I know this is for TS to fix rather than for this project to fix). This is how [`import-sort`](https://github.com/renke/import-sort) works (which is what we currently use and we want to migrate away from). 🤔

**Comment by thorn0** [comment]
> Then when you run organize-imports-cli --list-different, it will report differences. Is that the problem?

It was the problem. I implemented this flag in such a way that it ignores such differences. Give it a try.

> This makes me think that organize imports should not change any formatting

Removing and reordering things without changing formatting is tricky. Let's say we have this code:
```ts
import {
  bar,
  baz,
  bob,
  buildRouteActions,
  foo,
  handleDataFetchingError,
} from 'helpers/data-fetching';
```
and organize imports removes all the named imports from it but two:
```ts
import {
  bar,
  baz,
} from 'helpers/data-fetching';
```
It didn't change the formatting, but Prettier still is going to reprint this into
```ts
import { bar, baz } from 'helpers/data-fetching';
```

There are simpler cases of course. That check for formatting-only changes that I implemented for `--list-different` can probably be used in the main mode too for deciding if a file should be rewritten. But I'm really not sure this is needed.
