### ISSUE TITLE
tsconfig file with a different name

### ISSUE THREAD

**Issue by Shayan-To** [thorn0/organize-imports-cli#13]
In my project, the tsconfig file is not named `tsconfig.json`. Is it possible to run `organize-imports-cli` on the project in this situation?

And another hypothetical question. Is it possible to always give the command my project file? I was reading the source, and I saw that the ts project is being loaded. If so, I might want to give my project file, and run the action only on a few of the files (e.g. in a multi-project scenario that the project file to use would be ambiguous.).

**Comment by thorn0** [comment]
If you read the source, you know that the answer to both of your questions is 'no' as for now. If you have the time, a PR would be welcome.

**Comment by thorn0** [comment]
closed by #83
