### ISSUE TITLE
Upgrade to ts-morph@15 to support group-aware imports

### ISSUE THREAD

**Issue by FredKSchott** [thorn0/organize-imports-cli#190]
This new TS v4.7 feature is relevant to organize-imports-cli: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#groups-aware-organize-imports

```
// local code
import * as aaa from "./aaa";
import * as bbb from "./bbb";
import * as ccc from "./ccc";

// built-ins
import * as child_process from "child_process";
import * as fs from "fs";
import * as path from "path";

// some code...
```

We'd love to use this in Astro, but we need this feature due to a single order-dependent import that this CLI currently breaks. Upgrading to the latest version of ts-morph would fix this for us.

Thanks for the great project!

**Comment by thorn0** [comment]
v0.10.0 is on npm

**Comment by FredKSchott** [comment]
thanks!
