### ISSUE TITLE
`--check` flag?

### ISSUE THREAD

**Issue by bengry** [thorn0/organize-imports-cli#3]
Similar to Prettier, I'd expect a `--check` flag that exits with 0 if there are no files to modify, or 1 if there are. This is useful as a CI-ran script that verifies that all files are sorted.

Currently `--list-different` always exists with 0.

**Comment by thorn0** [comment]
> Currently --list-different always exists with 0.

Really?

**Comment by bengry** [comment]
Sorry, that was an error on my end, see https://github.com/thorn0/organize-imports-cli/issues/4#issuecomment-562233064. Closing this issue.
