### ISSUE TITLE
Organize a whole directory in a non-typescript project?

### ISSUE THREAD

**Issue by DaCurse** [thorn0/organize-imports-cli#30]
It looks like you have to have a tsconfig.json in order to be able to organize your whole project, and you have to specify specific files and can't specify a directory (e.g. `src/` or `src/*`) or a wildcard filename (e.g. `*.js` or `*`)

**Comment by dvcrn** [comment]
```
find src/ -iname '*.js' | xargs npx organize-imports-cli
```
