### ISSUE TITLE
Collision with prettier when imports are split into multiple lines

### ISSUE THREAD

**Issue by bengry** [thorn0/organize-imports-cli#4]
When there are a lot of imports, prettier opts to split them into multiple lines. e.g.:
```typescript
// foo.ts
import {
  Foo
  foo
  bar
  Baz
} from './some-file';

// ...
```

When running `organize-imports-cli --list-different` `foo.ts` is listed. This is of course true (and VS Code's built-in command also re-formats it when called), but together with #3, it makes a CI difficult to have as a check-only mechanism.

**Comment by thorn0** [comment]
Did you test this before submitting this issue? Please see #1. `--list-different` has a workaround exactly for this scenario.

**Comment by bengry** [comment]
I think it seemed to didn't work for me earlier since I ran `organize-imports-cli --list-different <path-to-file>`, which lists it, even if it's already sorted. So maybe that's the issue. When running on multiple files (via `lint-staged` or otherwise) it works as expected.

**Comment by thorn0** [comment]
> which lists it, even if it's already sorted

Could you please provide a minimal reproducible example for this?

**Comment by bengry** [comment]
Will try to repro later with something closer to my actual source, from a quick look it seems fine in a repro project I opened now.

**Comment by bengry** [comment]
Looks like this is working as expected.

I ended up using `eslint-plugin-simple-import-sort` and `eslint-plugin-import` instead.
It's not 1:1 what this does, but since we already use ESLint in our project (especially with the fix-on-save turned on in VS Code), and it is consistent, it made a lot of sense to just those instead.

Closing the issue as it doesn't reproduce, as you mentioned.
