### ISSUE TITLE
Allow for passing of tsconfig file path to CLI

### ISSUE THREAD

**Issue by mattpocock** [thorn0/organize-imports-cli#59]
This would allow us to use organize-imports-cli in our monorepo, running from root.

**Comment by thorn0** [comment]
But it works that way already, doesn't it?

**Comment by thorn0** [comment]
see README:

> Usage
> organize-imports-cli [--list-different] files...
> Files can be specific ts and js files or tsconfig.json, in which case the whole project is processed.
