### ISSUE TITLE
Support for not changing line endings

### ISSUE THREAD

**Issue by MHebes** [thorn0/organize-imports-cli#99]
When running this on my project, I get a ton of

```
warning: LF will be replaced by CRLF in my/file.ts.
The file will have its original line endings in your working directory
```

Support for keeping the line endings unchanged would be awesome.

**Comment by thorn0** [comment]
It [tries to do that already](https://github.com/thorn0/organize-imports-cli/blob/master/cli.js#L131
) unless you have an `.editorconfig` file with the `end_of_line` setting. If you have it, then this setting is respected.
